### ISSUE TITLE
[BUG] Unable to Initialize "Configuration class 'ConfigYAML' does not contain any (de-)serializable fields."

### ISSUE THREAD

**Issue by xCykrix** [Exlll/ConfigLib#21]
**Describe the Bug**
Unable to initialize a simple YAML Configuration without a more complex type.

**To Reproduce**
```java
@Configuration
public class ConfigYAML {
    @Comment("Test Config Value")
    private final String test = "HELLO WORLD";

    @Comment("Test Color Code")
    private final int prefixHexCode = 0x189EA9;
}
```
```
de.exlll.configlib.ConfigurationException: Configuration class 'ConfigYAML' does not contain any (de-)serializable fields.
        at de.exlll.configlib.ConfigurationSerializer.requireSerializableElements(ConfigurationSerializer.java:44) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
        at de.exlll.configlib.TypeSerializer.<init>(TypeSerializer.java:23) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
        at de.exlll.configlib.ConfigurationSerializer.<init>(ConfigurationSerializer.java:11) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
        at de.exlll.configlib.TypeSerializer.newSerializerFor(TypeSerializer.java:32) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
        at de.exlll.configlib.YamlConfigurationStore.<init>(YamlConfigurationStore.java:46) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
        at de.exlll.configlib.YamlConfigurations.update(YamlConfigurations.java:149) ~[Vouching-1.0-SNAPSHOT-shaded.jar:?]
```

**Expected behavior**
The configuration should initialize successfully even if no complex or custom serializers are present.

**Additional context**
I know this is mainly designed for complex configurations, however, I was unable to get a simple string only, such as a messages.yml, to generate without an error.

**Comment by xCykrix** [comment]
That most definitely does! I was feeling like it was just something I overlooked but was stuck on. Thank you!
